### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by zakiyousufi** [zakiyousufi/Rental-API#26]
### In this Milestone I @zakiyousufi  and my partners @Profsain @soulemanou-software @UsirusenIkon 
**_worked togather and create our kanban board following these_** [ requirements ](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md) 
Link to the [github_projects/rental-house/kanban-board](https://github.com/users/zakiyousufi/projects/4/views/1)

Screenshot of kanban board
![new kanban](https://user-images.githubusercontent.com/87229464/222793605-7bccf2b4-de00-4327-9a32-d5c89226369a.JPG)

**Comment by mcrd25** [comment]
Hi Team, 

Great work so far👏 
However there are some issues preventing me from giving the 👍 


## Highlights
- Each team member has tasks assigned ✔️ 
- Realistic weight to tasks assigned ✔️ 

## Required Changes
- you ought to have descriptions for all tasks. This is currently not the case ✖️ 
-  There ought to be an equitable distribution of weights for each team member where the number of assigned points should be equal (+/- 5 points) for each member. Currently there is a case where one member has aroudn 30 and another 21. The difference should not be greater than 5. ✖️ 

## Optional suggestions
- [OPTIONAL] maybe you can consider adding labels. This may help with filtering different types of tasks easily. ❓ 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zakiyousufi** [comment]
Hello @mcrd25 
Thanks for your kind review and feedback

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- completed all requested changes ✔️ 

## Optional suggestions
- [OPTIONAL] Consider adding labels ❓ 

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zakiyousufi** [comment]
@mcrd25 
Hi again,
Thanks for approval and feedback that you provided I will add the `labels` for issues
